# Generated by Django 4.2.2 on 2023-06-15 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0002_wallet_balance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "crypto")},
        ),
    ]
