# Generated by Django 4.2.2 on 2023-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallet_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
