# Generated by Django 4.2.2 on 2023-06-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
    ]
