# Generated by Django 4.2.2 on 2023-06-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_super_user",
            field=models.BooleanField(default=False),
        ),
    ]
