# Generated by Django 4.2.2 on 2023-06-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_super_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_super_user",
            new_name="is_superuser",
        ),
    ]
