# Generated by Django 4.2.2 on 2023-06-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_is_super_user_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
