# Generated by Django 4.2.2 on 2023-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255, unique=True)),
                ("price_buy", models.DecimalField(decimal_places=10, max_digits=20)),
                ("price_sell", models.DecimalField(decimal_places=10, max_digits=20)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("past24", models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
