# Generated by Django 4.2.2 on 2023-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptocurrency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="past24",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
